### PR TITLE
Modifies configureToolbarBlockOptions to search in blockButtons prop instead of BLOCK_BUTTONS; likewise with configureToolbarInlineOptions

### PR DESCRIPTION
**Pull request by kylebebak**
Adds H1 and H2 block buttons to toolbar. Currently there's no way to add these to toolbar, and now there is.

Of course users can trivially remove them by passing something like this for `toolbarConfig`:

```js
toolbarConfig = {
  block: ['header-three', 'unordered-list-item', 'ordered-list-item', 'todo'],
  inline: ['BOLD', 'ITALIC', 'UNDERLINE', 'hyperlink'],
}
```

### CODE REVIEW

**Comment by brijeshb42** [comment]
There is a way to do this right now, but not through `toolbarConfig`. You can directly pass your own block buttons array as prop to the editor.

```js
// if you want to keep the default buttons,
import { BLOCK_BUTTONS } from 'medium-draft';

const myBlockButtons = [{
    label: 'H1',
    style: 'header-one',
    icon: 'header',
    description: 'Heading 1',
  },
  {
    label: 'H2',
    style: 'header-two',
    icon: 'header',
    description: 'Heading 2',
}].concat(BLOCK_BUTTONS);

// in your component
<Editor blockButtons={myBlockButtons} ... />
```

**Comment by kylebebak** [comment]
Ah, thanks! It might be a good idea to document the `blockButtons` prop in the README using the example you just wrote here.

Still, `blockButtons` is pretty tough prop to use, because if you want to add some block buttons and **remove** or **reorder** others (my use case), you're going to have to do some weird stuff with splice or slice or pulling items out of `BLOCK_BUTTONS` and building a new array with them.

I think the two props are complementary. `toolbarConfig` makes it easy to remove and reorder default buttons, and `blockButtons` other makes it possible to change the icon, description and label of default block buttons.

I think the H1 and H2 block buttons ought to be added to the default array, but I realize this would be a backwards incompatible change in the API, because it would add two new buttons to a bunch of users' toolbars (buttons many of them would surely want to have).

Ah, actually I just thought of another solution, which would be backwards compatible.

Change this:
```js
configureToolbarBlockOptions(toolbarConfig) {
  return toolbarConfig && toolbarConfig.block
    ? toolbarConfig.block.map(type => BLOCK_BUTTONS.find(button => button.style === type))
      .filter(button => button !== undefined)
    : this.props.blockButtons;
}
```

To this:
```js
configureToolbarBlockOptions(toolbarConfig) {
  return toolbarConfig && toolbarConfig.block
    ? toolbarConfig.block.map(type => this.props.blockButtons.find(button => button.style === type))
      .filter(button => button !== undefined)
    : this.props.blockButtons;
}
```

`this.props.blockButtons` already defaults to `BLOCK_BUTTONS`, so this wouldn't change existing behavior, **but it would allow** users to combine the two props. In other words, they could do what you did above, adding two buttons, and also pass a `toolbarConfig` to remove/reorder others.

Of course we could do the same thing with `configureToolbarInlineOptions`.

This is a small change but I think it would improve the API. Which of the two solutions do you think would be better?

**Comment by brijeshb42** [comment]
If you change to what you suggested, then you will have to remove your changes in `toolbar.js` so that the existing behavior does not change. If that works, I'll merge your modifications and publish a new version

**Comment by kylebebak** [comment]
Yeah, I'll do that!

**Comment by kylebebak** [comment]
And yeah, I still think it would be a good idea to add the code you showed me above to the docs, and explain how it can be combined with `configureToolbar...Options` to get any sort of custom toolbar.

Want me to add that to the docs myself? You could merge this PR and then I could open another one later.

**Comment by brijeshb42** [comment]
You should add the docs in this PR itself

**Comment by kylebebak** [comment]
Ok, done!

I tried to be explicit without writing too much.

**Comment by kylebebak** [comment]
Cool, thank you... Looking forward to the next release!

**Pull request merged**
