### PR TITLE
Make AddButton extensible

### PR DESCRIPTION
**Pull request by apuntovanini**
In order to be able to customize addButton with this PR you can now pass a custom AddButton component

### CODE REVIEW

**Comment by apuntovanini** [comment]
I temporarly added lib folder to git repo because I needed to test implementation in our project. If you're planning to merge it I'll remove it.

**Comment by apuntovanini** [comment]
@brijeshb42 what do you think? I'm progressively making medium-editor more customizable, with custom buttons and custom scss

**Comment by brijeshb42** [comment]
@apuntovanini I will update you by tomorrow. Anyways, I don't think `lib` folder should be merged in main branch. If you can update that, it would be great.

**Comment by apuntovanini** [comment]
Yep, sure, but I wanted to test in my projects if everything was working fine, and couldn't use lib since its only on npm (or probably i just messed up). I'll remove it right now

**Comment by brijeshb42** [comment]
Actually there are quite a lot of changes. It may take more time to for me to give you and update, mostly because you have changed versions of a lot of dependencies. I will test and update.

**Comment by apuntovanini** [comment]
Yes, sure, no worries. I tested the new deps alreay, but take a look if it fits and works
Thanks!

**Comment by apuntovanini** [comment]
@brijeshb42 any news on this? I think that despite the lib folder (which I'll remove after your feedback), it doesn't change the behaviour and it adds a feature which is in line with your new branch, isnt' it?

**Pull request closed without merging**
